from datetime import datetime, timezone, timedelta
from typing import List, Tuple, Callable, Any

import util
from scanners.scanner import App


def entry_to_string(app: App) -> str:
    """Render a single app entry as a markdown list item."""
    url = app.urls[0] if app.urls else '#'
    name = app.name or 'unknown'
    line = f" * [{name}]({url})"

    if app.scanner == "FDroidScanner":
        line += " `fdroid`"
    if app.desc:
        line += f" - {app.desc}"
    line += "\n"
    return line


def _get_sort_key_and_reverse(mode: str) -> Tuple[Callable[[App], Any], bool]:
    mode = (mode or 'name').lower()

    if mode == 'popularity':
        # sort by popularity descending, then name asc
        def key(a: App) -> Any:
            return -(a.popularity or 0), (a.name or '').lower()
        return key, False

    if mode == 'updated':
        # sort by last_updated (most recent first)
        def key(a: App) -> Any:
            dt = util.make_aware(a.last_updated)
            return dt or datetime.fromtimestamp(0, tz=timezone.utc)
        return key, True

    # default: name (ascending)
    def key(a: App) -> Any:
        return (a.name or '').lower()
    return key, False


def section_to_string(title: str, apps: List[App], sort_mode: str = 'name') -> str:
    """Render a titled section showing recently-updated and older apps.

    - Apps updated within the last 90 days go into the "new" group.
    - The rest go into the "old" group.
    The `sort_mode` controls how items within each subgroup are sorted.
    Supported modes: 'name' (default), 'popularity', 'updated'.
    """
    report = "\n"
    now = datetime.now(timezone.utc)
    recent_cutoff = timedelta(days=90)

    new: List[App] = []
    old: List[App] = []
    for app in apps:
        last = util.make_aware(app.last_updated)
        if last is not None and (now - last) <= recent_cutoff:
            new.append(app)
        else:
            old.append(app)

    keyfunc, reverse = _get_sort_key_and_reverse(sort_mode)

    new.sort(key=keyfunc, reverse=reverse)
    old.sort(key=keyfunc, reverse=reverse)

    if new or old:
        report += f"### {title}\n\n"

    def _render_group(group_apps: List[App]) -> str:
        out = ""
        # Separate original and non-original content
        original = [a for a in group_apps if bool(a.is_original_content)]
        non_original = [a for a in group_apps if not bool(a.is_original_content)]

        # split original items by popularity (treat missing popularity as zero)
        original_nonzero = [a for a in original if (a.popularity or 0) > 0]
        original_zero = [a for a in original if (a.popularity or 0) == 0]

        for app in original_nonzero:
            out += entry_to_string(app)

        if non_original:
            out += "\n<details>\n<summary>Non-original content</summary>\n\n"
            for app in non_original:
                out += entry_to_string(app)
            out += "</details>\n"

        if original_zero:
            out += "\n<details>\n<summary>No GitHub stars</summary>\n\n"
            for app in original_zero:
                out += entry_to_string(app)
            out += "</details>\n"

        return out

    if new:
        report += "#### Updated in the last 3 months\n\n"
        report += _render_group(new)

    if old:
        report += "\n#### Updated more than 3 months ago\n\n"
        report += _render_group(old)

    return report


def write_report(report_path: str, apps: List[App]) -> None:
    """Write the generated report to disk (overwrites any existing file)."""
    header = (
        "## Scan results\n"
        "> [!IMPORTANT]\n"
        "> This file is automatically generated. Do not edit.\n\n"
        "This document tracks all GitHub repos and F-Droid apps that make use of Shizuku in some way but are not yet "
        "listed in the awesome-shizuku list. Please note that many of these apps are often incomplete or sometimes even false positives.\n"
        "Typically, these apps will be added to the list as soon as possible; however, unfinished apps are usually left in this document until they reach a usable state.\n\n"
    )

    report = header
    report += "Entries are sorted by name and grouped into a separate category if the attached link has no downloadable releases.\n\n"
    report += section_to_string("Apps with releases", [a for a in apps if a.has_downloads], sort_mode='name')
    report += section_to_string("Apps with no releases", [a for a in apps if not a.has_downloads], sort_mode='name')

    with open(report_path, 'w') as f:
        f.write(report)


def write_sorted_reports(sorted_report_path: str, apps: List[App]) -> None:
    """Write a single file containing multiple sorting modes, each inside a <details> block.

    The output will contain one <details> block per supported sort mode. Inside each block the
    "Apps with releases" and "Apps with no releases" sections are rendered using that sort mode.
    """
    header = (
        "## Scan results (alternate sorts)\n"
        "> [!IMPORTANT]\n"
        "> This file is automatically generated. Do not edit.\n\n"
    )

    modes = [
        ('popularity', 'Sorted by popularity (most → least)'),
        ('updated', 'Sorted by last updated (most recent first)'),
    ]

    out = header
    out += "The file contains the same app entries shown in different sorting orders. Expand a block to view that ordering.\n\n"

    for mode_key, mode_label in modes:
        out += f"<details>\n<summary>{mode_label}</summary>\n\n"
        out += section_to_string("Apps with releases", [a for a in apps if a.has_downloads], sort_mode=mode_key)
        out += section_to_string("Apps with no releases", [a for a in apps if not a.has_downloads], sort_mode=mode_key)
        out += "</details>\n\n"

    with open(sorted_report_path, 'w') as f:
        f.write(out)
