name: Run scanner

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      cache-key: crawler-cache-new

    steps:
    - uses: actions/checkout@v5
      with:
        repository: thepbone/app-crawler

    - uses: actions/checkout@v5
      with:
        repository: thepbone/awesome-shizuku
        path: './list'
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: cache/
        key: ${{ env.cache-key }}
    
    - name: Run crawler
      env: 
        GITHUB_AUTH: ${{ secrets.GH_PAT }}
      run: |
        python main.py ./list
        cat SUMMARY.md >> $GITHUB_STEP_SUMMARY
        cat SUMMARY_RANKED.md >> $GITHUB_STEP_SUMMARY

    - name: Delete previous cache
      if: ${{ steps.cache-restore.outputs.cache-hit }}
      continue-on-error: true
      run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ env.cache-key }}" --confirm
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: cache/
        key: ${{ env.cache-key }}

    - name: Publish summary changes
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Update SUMMARY*.md
        file_pattern: ./SUMMARY*.md
        commit_author: "Tim Schneeberger <38386967+timschneeb@users.noreply.github.com>"

        
